DROP DATABASE IF EXISTS `amselnutradb`;

-- MySQL Script generated by MySQL Workbench
-- Sun Aug  6 15:40:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema amselnutradb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema amselnutradb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `amselnutradb` DEFAULT CHARACTER SET utf8 ;
USE `amselnutradb` ;

-- -----------------------------------------------------
-- Table `amselnutradb`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amselnutradb`.`Departments` (
  `DepartmentID` INT NOT NULL AUTO_INCREMENT,
  `DepartmentName` VARCHAR(45) NULL DEFAULT 'Default Department',
  `Description` VARCHAR(100) NULL DEFAULT 'Department Description',
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `CreateBy` INT NULL DEFAULT 0,
  `Updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedBy` INT NULL DEFAULT 0,
  PRIMARY KEY (`DepartmentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amselnutradb`.`Positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amselnutradb`.`Positions` (
  `PositionID` INT NOT NULL AUTO_INCREMENT,
  `Position` VARCHAR(45) NULL DEFAULT 'Position',
  `Description` VARCHAR(100) NULL DEFAULT 'Position Description',
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` INT NULL DEFAULT 0,
  `Updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedBy` INT NULL DEFAULT 0,
  PRIMARY KEY (`PositionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amselnutradb`.`WorkingArea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amselnutradb`.`WorkingArea` (
  `WorkingAreaID` INT NOT NULL AUTO_INCREMENT,
  `Zone` VARCHAR(45) NOT NULL,
  `Area` VARCHAR(45) NOT NULL,
  `IsActive` ENUM('1', '0') NOT NULL DEFAULT '1',
  `Created` DATETIME NULL,
  `CreateBy` INT NULL,
  `Updated` DATETIME NULL,
  `UpdatedBy` INT NULL,
  PRIMARY KEY (`WorkingAreaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amselnutradb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amselnutradb`.`Users` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  `FirstName` VARCHAR(100) NOT NULL DEFAULT 'FirstName',
  `LastName` VARCHAR(100) NOT NULL DEFAULT 'LastName',
  `NickName` VARCHAR(100) NULL DEFAULT 'NickName',
  `IsSalesPerson` ENUM('1', '0') NOT NULL DEFAULT '0',
  `IsApprovable` ENUM('1', '0') NOT NULL DEFAULT '0',
  `WorkingID` INT NOT NULL DEFAULT 0,
  `DepartmentID` INT NOT NULL DEFAULT 0,
  `PositionID` INT NOT NULL DEFAULT 0,
  `CreatedBy` VARCHAR(100) NULL DEFAULT 'System',
  `Created` DATETIME NULL,
  `UpdatedBy` VARCHAR(100) NULL DEFAULT 'System',
  `Updated` DATETIME NULL,
  `ContactNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC),
  INDEX `DepartmentID_IDX_idx` (`DepartmentID` ASC),
  INDEX `PositionID_Key_idx` (`PositionID` ASC),
  INDEX `WorkingID_Key_idx` (`WorkingID` ASC),
  CONSTRAINT `DepartmentID_Key`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `amselnutradb`.`Departments` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PositionID_Key`
    FOREIGN KEY (`PositionID`)
    REFERENCES `amselnutradb`.`Positions` (`PositionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `WorkingID_Key`
    FOREIGN KEY (`WorkingID`)
    REFERENCES `amselnutradb`.`WorkingArea` (`WorkingAreaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
